import type { ArtifactDefinition } from "./types";

export const gravityCoreArtifact: ArtifactDefinition = {
  id: "001",
  archiveCode: "VA-001/G",
  title: "GRAVITY CORE",
  classification: "GRAVITATIONAL ANOMALY",
  status: "UNSTABLE",
  origin: "UNKNOWN",
  containment: "ACTIVE",
  summary: "MASS SIGNATURE EXCEEDS CONTAINMENT MODEL. SOURCE EVENT REDACTED.",
  readings: [
    { label: "STATUS", value: "UNSTABLE", accent: true },
    { label: "CLASS", value: "GRAVITATIONAL ANOMALY" },
    { label: "ORIGIN", value: "UNKNOWN" },
    { label: "CONTAINMENT", value: "ACTIVE" },
  ],
  anomalyLabel: "FIELD DEVIATION",
  anomalyDormant: "RISING  +0.021",
  anomalyActive: "RISING  +0.083",
  lifecycle: { visibleFrom: 0, entryFrom: 0, activationFrom: 0.02, inspectionFrom: 0.1, exitAfter: 0.31 },
  camera: { entryAt: 0, inspectionAt: 0.18, exitAt: 0.34 },
  quality: {
    desktop: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 1 },
    tablet: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 0 },
    mobile: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 0 },
  },
  reducedMotion: { activationScale: 0, surfaceMotion: 0, pointerEnabled: false },
};

export const liquidMirrorArtifact: ArtifactDefinition = {
  id: "002",
  archiveCode: "VA-002/M",
  title: "LIQUID MIRROR",
  classification: "OPTICAL ANOMALY",
  status: "OBSERVATIONAL",
  origin: "UNRESOLVED",
  containment: "VISUAL ISOLATION",
  summary: "REFLECTED SPACE DIVERGES FROM CURRENT OBSERVATION. SUBJECT CORRELATION INCOMPLETE.",
  readings: [
    { label: "STATUS", value: "OBSERVATIONAL", accent: true },
    { label: "CLASS", value: "OPTICAL ANOMALY" },
    { label: "ORIGIN", value: "UNRESOLVED" },
    { label: "CONTAINMENT", value: "VISUAL ISOLATION" },
    { label: "REFLECTION LATENCY", value: "+0.73 SEC", accent: true },
    { label: "SUBJECT MATCH", value: "FAILED", accent: true },
  ],
  anomalyLabel: "RETURN IMAGE",
  anomalyDormant: "RECORD LOCKED",
  anomalyActive: "PARTIAL / NONLOCAL",
  lifecycle: { visibleFrom: 0.4, entryFrom: 0.44, activationFrom: 0.48, inspectionFrom: 0.54, exitAfter: 0.575 },
  camera: { entryAt: 0.43, inspectionAt: 0.54, exitAt: 0.575 },
  quality: {
    desktop: { membraneSegments: 56, reflectionLayers: 3, pointerStrength: 1 },
    tablet: { membraneSegments: 40, reflectionLayers: 2, pointerStrength: 0.45 },
    mobile: { membraneSegments: 28, reflectionLayers: 1, pointerStrength: 0 },
  },
  reducedMotion: { activationScale: 0.35, surfaceMotion: 0, pointerEnabled: false },
};

export const temporalRingArtifact: ArtifactDefinition = {
  id: "003",
  archiveCode: "VA-003/T",
  title: "TEMPORAL RING",
  classification: "TEMPORAL ANOMALY",
  status: "DESYNCHRONIZED",
  origin: "UNKNOWN",
  containment: "CHRONOLOGY LOCK",
  summary: "RECORDED EVENT COUNT EXCEEDS OBSERVED HISTORY. LOCAL SEQUENCE CANNOT BE VERIFIED.",
  readings: [
    { label: "STATUS", value: "DESYNCHRONIZED", accent: true },
    { label: "CLASS", value: "TEMPORAL ANOMALY" },
    { label: "LOCAL TIME", value: "+04.731 SEC", accent: true },
    { label: "PHASE COHERENCE", value: "63%" },
    { label: "OBSERVED EVENTS", value: "12" },
    { label: "RECORDED EVENTS", value: "13", accent: true },
  ],
  anomalyLabel: "OBSERVATION WINDOW",
  anomalyDormant: "RESTRICTED",
  anomalyActive: "EVENT 13 / UNOBSERVED",
  lifecycle: { visibleFrom: 0.59, entryFrom: 0.62, activationFrom: 0.65, inspectionFrom: 0.7, exitAfter: 0.76 },
  camera: { entryAt: 0.62, inspectionAt: 0.7, exitAt: 0.76 },
  quality: {
    desktop: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 1, echoSamples: 3, temporalSegments: 6 },
    tablet: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 0.45, echoSamples: 2, temporalSegments: 5 },
    mobile: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 0, echoSamples: 1, temporalSegments: 4 },
  },
  reducedMotion: { activationScale: 0.55, surfaceMotion: 0, pointerEnabled: false },
};

export const neuralRelicArtifact: ArtifactDefinition = {
  id: "004",
  archiveCode: "VA-004/N",
  title: "NEURAL RELIC",
  classification: "SYNTHETIC BIOLOGICAL ANOMALY",
  status: "ADAPTIVE",
  origin: "UNRECORDED",
  containment: "COGNITIVE ISOLATION",
  summary: "RESPONSE LATENCY DECREASES UNDER DIRECT OBSERVATION. ADAPTIVE INTENT CANNOT BE EXCLUDED.",
  readings: [
    { label: "STATUS", value: "ADAPTIVE", accent: true },
    { label: "CLASS", value: "SYNTHETIC BIOLOGICAL" },
    { label: "ACTIVE NODES", value: "147 → 151", accent: true },
    { label: "RESPONSE LATENCY", value: "420MS → 211MS", accent: true },
    { label: "PATTERN MATCH", value: "OBSERVER" },
    { label: "TOPOLOGY", value: "CHANGING" },
  ],
  anomalyLabel: "TOPOLOGY CHANGE",
  anomalyDormant: "MONITORING",
  anomalyActive: "UNAUTHORIZED",
  lifecycle: { visibleFrom: 0.77, entryFrom: 0.795, activationFrom: 0.825, inspectionFrom: 0.865, exitAfter: 0.895 },
  camera: { entryAt: 0.795, inspectionAt: 0.865, exitAt: 0.895 },
  quality: {
    desktop: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 1, branchCount: 22, signalCount: 5 },
    tablet: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 0.4, branchCount: 17, signalCount: 3 },
    mobile: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 0, branchCount: 11, signalCount: 2 },
  },
  reducedMotion: { activationScale: 0.7, surfaceMotion: 0, pointerEnabled: false },
};

export const voidArtifact: ArtifactDefinition = {
  id: "005",
  archiveCode: "VA-005/V",
  title: "THE VOID",
  classification: "SPATIAL ABSENCE ANOMALY",
  status: "NONLOCAL",
  origin: "UNRESOLVED",
  containment: "GEOMETRIC ISOLATION",
  summary: "LOCAL VOLUME RETURNS NO SPATIAL MEASUREMENT. ADJACENT STRUCTURE IS BEING SUBTRACTED.",
  readings: [
    { label: "STATUS", value: "NONLOCAL", accent: true },
    { label: "CLASS", value: "SPATIAL ABSENCE" },
    { label: "VOLUME", value: "UNDEFINED", accent: true },
    { label: "BOUNDARY", value: "INCONSISTENT" },
    { label: "DEPTH RETURN", value: "NULL", accent: true },
    { label: "STRUCTURAL LOSS", value: "INCREASING", accent: true },
  ],
  anomalyLabel: "LOCAL GEOMETRY",
  anomalyDormant: "NO RETURN",
  anomalyActive: "EDGE POSITION INCONSISTENT",
  lifecycle: { visibleFrom: 0.905, entryFrom: 0.925, activationFrom: 0.945, inspectionFrom: 0.975, exitAfter: 1.08 },
  camera: { entryAt: 0.92, inspectionAt: 0.975, exitAt: 1.08 },
  quality: {
    desktop: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 0.42, voidParticles: 52, fractureSeams: 7 },
    tablet: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 0.22, voidParticles: 34, fractureSeams: 5 },
    mobile: { membraneSegments: 0, reflectionLayers: 0, pointerStrength: 0, voidParticles: 20, fractureSeams: 4 },
  },
  reducedMotion: { activationScale: 0.78, surfaceMotion: 0, pointerEnabled: false },
};
